### ISSUE TITLE
Not able to access ServiceRemotingServiceEvents in Microsoft.ServiceFabric.Services.Remoting.V2.Runtime namespace

### ISSUE THREAD

**Issue by cpiitb** [Microsoft/service-fabric-services-and-actors-dotnet#105]
I am looking for a way to listen ReceiveRequest or SendResponse events while communicating with different services using ServiceRemoting.

Earlier we were able to do that with below events.

ServiceRemotingServiceEvents.ReceiveRequest
ServiceRemotingServiceEvents.SendResponse

These events were available in Microsoft.ServiceFabric.Services.Remoting.V2.Runtime namespace.
Now I am not able to find these in this namespace. Compiler gives below error.

Error	CS0122	'ServiceRemotingRequestEventArgs' is inaccessible due to its protection level	

Can anyone please help me with this?
Is there any other way to get these events?

I am using below packages. 

I am using below nuget packages.
package id="Microsoft.ServiceFabric" version="6.1.480" targetFramework="net461"
package id="Microsoft.ServiceFabric.Data" version="3.0.480" targetFramework="net461"
package id="Microsoft.ServiceFabric.Diagnostics.Internal" version="3.0.480" targetFramework="net461"
package id="Microsoft.ServiceFabric.FabricTransport.Internal" version="3.0.480" targetFramework="net461"
package id="Microsoft.ServiceFabric.Services" version="3.0.480" targetFramework="net461"
package id="Microsoft.ServiceFabric.Services.Remoting" version="3.0.480" targetFramework="net461"

Thanks in advance.

**Comment by amanbha** [comment]
@cpiitb Microsoft.ServiceFabric.Services.Remoting.V2.Runtime.ServiceRemotingServiceEvents was introduced in 3.0.467 version of Microsoft.ServiceFabric.Services.Remoting nuget package and it has been internal since then. Could you please explain where you were able to access this?

**Comment by cpiitb** [comment]
@amanbha I saw that AppInsight project for service fabric is doing the same. 
Link: https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/master/src/ApplicationInsights.ServiceFabric.Native.Shared/RequestTrackingModule/ServiceRemotingServerEventListener.cs

As this event is internal we can't access it. Is there any other way I can call my function whenever service received any request?

**Comment by amanbha** [comment]
These methods are in the hot path of request processing, any delay in these events will impact the performance. These methods are internal only and are made visible to ApplciationInsights binary to enable the functionality, I worked with ApplicationInsights team to ensure that ApplicitonInsight's subscription to these events doesn't block it and process these events in an asynchronous manner. For now we don't have any plans to make these public as these apis are prone to changes. Any reason you cant use ApplicationInsights in your service?

If you want to notified when your service receives a request, you can do that by writing your own custom message handler and hooking up events.
Please see following sample which demonstrates this: https://github.com/amanbha/servicefabric/tree/master/samples/ServiceCustomMessageHandler

**Comment by cpiitb** [comment]
Thanks amanbha. I will give it a try and will update the thread.

**Comment by cpiitb** [comment]
Thanks amanbha. It works fine. I still have one question.
When service send/recieve IServiceRemotingRequestMessage message.
Can I pre calculate the IServiceRemotingRequestMessageHeader.InterfaceId for a method call?
I saw there is IdUtilHelper class in ApplicationInsight project mentioned above, which is calculating interfaceId. But these two Ids are different. 

Can you please let me know if there is any way I can get InterfaceIds?

**Comment by amanbha** [comment]
@cpiitb yes, you can extract it as:
var interfaceId = requestMessage.GetHeader().InterfaceId;

**Comment by cpiitb** [comment]
@amanbha  I know this part. But I want to get the method name. 

In below project we are getting it using below statement. 

methodName = this.methodNameProvider.GetMethodName(messageHeaders.InterfaceId, messageHeaders.MethodId);

https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/master/src/ApplicationInsights.ServiceFabric.Native/Net45/CorrelatingServiceRemotingClient.cs

But It is not working in my case. messeageHEaders.InrefaceId is different than what is comupteb by below method.
int interfaceId = IdUtilHelper.ComputeId(interfaceType);

in this file.

https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/master/src/ApplicationInsights.ServiceFabric.Native/Net45/MethodNameProvider.cs

 Is there any other way to get the method name from the requestMessage?

**Comment by amanbha** [comment]
@cpiitb Method name information is not available in requestMessage. ApplicationInsight's  IdUtilHelper.ComputeId which you pointed to is doing reflection to call older methods(used in V1 remoting), the code which you pointed to is using V1 remoting. The correct method to reflect is ComputeIdWithCRC, but that's all implementation detail and prone to change.
It seems like you are trying to do what ApplicationInsights is doing, is there a reason you cant use ApplicationInsights?
ApplicationInsights did that as their code is generic for everyone. If you control your client and services, you can achieve similar thing by not relying on internal implemenation, you can add the method method to CallContext in your method, retrieve from CallContext and add to the header in your [CustomRemotingClient implementation](https://github.com/amanbha/servicefabric/blob/master/samples/ActorCustomMessageHandler/ActorClient/CustomActorRemotingClient.cs#L42). On the service side you can fetch it from Header.

**Comment by amanbha** [comment]
@cpiitb I am closing this issue, if you have further questions, please feel free to reopen.
