### ISSUE TITLE
Please include MethodName in public interface

### ISSUE THREAD

**Issue by Expecho** [Microsoft/service-fabric-services-and-actors-dotnet#128]
When writing custom message interception it would be really nice if we can do something with the name of the method that is invoked. Currently we have only access to the InterfaceId and MethodId. I see there is a public property MethodName but it is not included in the public interface `IServiceRemotingRequestMessageHeader`. Why is that? 

https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/blob/0e8d0ed6ebd3fa34248fbb050780468f1ce9d744/src/Microsoft.ServiceFabric.Services.Remoting/V2/ServiceRemotingRequestMessageHeader.cs#L55

**Comment by amanbha** [comment]
@Expecho this has been added to [IServiceRemotingRequestMessageHeader](https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/blob/0e8d0ed6ebd3fa34248fbb050780468f1ce9d744/src/Microsoft.ServiceFabric.Services.Remoting/V2/IServiceRemotingRequestMessageHeader.cs) and will be part of the next release.

**Comment by Expecho** [comment]
Ah great to hear, thanks! (psst … any ETA?)

**Comment by amanbha** [comment]
Tentative date is ~3weeks
