### ISSUE TITLE
Please add CreateNonIServiceProxy to the IServiceProxyFactory interface

### ISSUE THREAD

**Issue by Expecho** [Microsoft/service-fabric-services-and-actors-dotnet#129]
The public interface `IServiceProxyFactory` [here](https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/blob/0e8d0ed6ebd3fa34248fbb050780468f1ce9d744/src/Microsoft.ServiceFabric.Services.Remoting/Client/IServiceProxyFactory.cs ) does not contain the method `CreateNonIServiceProxy` making it hard to use the interface for unit testing purposes if you depend on the `CreateNonIServiceProxy` method.

**Comment by suchiagicha** [comment]
Sure. Would you be interested in submitting PR?

**Comment by Expecho** [comment]
Sure, no problem. I'll get to it tomorrow.

**Comment by Expecho** [comment]
I think we are running into problems. The V1 remoting stack does not support the `CreateNonIServiceProxy` method. Most interfaces and classes have a separate V1 and V2 version, except for the single `IServiceProxyFactory` interface that is shared by the internal classes `Microsoft.ServiceFabric.Services.Remoting.V2.Client.ServiceProxyFactory`  and `Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceProxyFactory` and the public class Microsoft.ServiceFabric.Services.Remoting.Client.ServiceProxyFactory.

Now, since `Microsoft.ServiceFabric.Services.Remoting.V1.Client.ServiceProxyFactory` is internal we could opt for just create an implementation of `IServiceProxyFactory.CreateNonIServiceProxy` that throws a NotImplementedException for example since it won't be accessed anywhere and especially not from outside the assembly.

Any thoughts on this?

**Comment by suchiagicha** [comment]
Sounds good  :)
