### ISSUE TITLE
Question: Looking for guidance on replica density

### ISSUE THREAD

**Issue by veatcha** [Microsoft/service-fabric-services-and-actors-dotnet#136]
I'm looking for some guidance in terms of replica density on our Service Fabric cluster after reading the comments on [another issue](https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/issues/96) - specifically are there guidelines we should be aware of and/or specific things we can monitor for getting some visibility?

We've seen messages of this variety with more frequency lately in our Actors, both during application updates and cluster infrastructure/update operations:

> The api IStatefulServiceReplica.ChangeRole(P) on node XXX is stuck

During under our heaviest load, our cluster doesn't show any sign of stress in CPU, RAM, disk or network - but I'm unclear on how much additional stress is caused moving replicas/state between nodes during upgrades.

Based on the comments in that other issue, I suspect we have too many replicas per node, but we want to be able to effectively monitor for that so we don't need to be reactive in making adjustments.

Thanks,
Andrew

**Comment by amanbha** [comment]
@veatcha  During an upgrade an entire Upgrade Domain(UD) can be down. So if you have 20 nodes across 4 Upgrade domains, 5 nodes in one UD can be down so you will have to account for replica density during the upgrades as well. There is no hard limit on # of replicas, its upper bounded by physical resources. But what I have observed that, try to keep replica density to ~80(account for one UD down here in the cluster) for each node with performance testing that the nodes will be able handle the loads.

**Comment by veatcha** [comment]
Thanks @amanbha
