### ISSUE TITLE
Actor reminders not being triggered

### ISSUE THREAD

**Issue by lindgrend** [Microsoft/service-fabric-services-and-actors-dotnet#149]
**Describe the bug**
On our production environment we are noticing that sometimes Actor reminders are not being received.
We have created a small project that creates actors and sets reminders this was running fine for 4 days but then we saw the same kind of behaviour there.

[Failing reminders](https://ibb.co/ewM3QU)

Both booleans should be true if both the single reminder as well as where the retry-mechanism is used. Due to one being a reminder with retries makes me believe that it has failed to be saved to the state(we are examining this at the moment) .

**To Reproduce**
Test project: [GIT](https://github.com/lindgrend/ActorIssue)

We use the following code to register the reminders:

``` 
public async Task StartReminder()
{
    _table = GetTable();

    Random rnd = new Random();

    ReminderEntity newEntity = new ReminderEntity()
    {
        PartitionKey = "reminder",
        RowKey = this.GetActorId().GetStringId().ToString(),
        ReminderOnceFired = false,
        ReminderOnceDate = DateTime.UtcNow.AddMinutes(rnd.Next(1, 5)),
        ReminderRecurringFired = false,
        ReminderRecurringDate = DateTime.UtcNow.AddMinutes(rnd.Next(1, 5))
    };


    await base.RegisterReminderAsync("reminderOnce",
        null,
        newEntity.ReminderOnceDate.Subtract(DateTime.UtcNow),
        TimeSpan.FromMilliseconds(-1));

    await base.RegisterReminderAsync("reminderRecurring",
        null,
        newEntity.ReminderRecurringDate.Subtract(DateTime.UtcNow),
        TimeSpan.FromSeconds(10));


    await InsertRecordToTable(_table, newEntity);

}
```
ReceiveReminderAsync:
```
 public async Task ReceiveReminderAsync(string reminderName, byte[] state, TimeSpan dueTime, TimeSpan period)
{
    _table = GetTable();

    ActorEventSource.Current.ActorMessage(this, "Reminder");

    var entity = new DynamicTableEntity("reminder", this.GetActorId().GetStringId().ToString());
    switch (reminderName)
    {
        case "reminderOnce":
            entity.ETag = "*";
            entity.Properties.Add("ReminderOnceFired", new EntityProperty(true));
            entity.Properties.Add("ReminderOnceDate", new EntityProperty(DateTime.UtcNow));
            await UpdateRecordToTable(_table, entity);

            break;

        case "reminderRecurring":
            entity.ETag = "*";
            entity.Properties.Add("ReminderRecurringFired", new EntityProperty(true));
            entity.Properties.Add("ReminderRecurringDate", new EntityProperty(DateTime.UtcNow));
            await UpdateRecordToTable(_table, entity);

            IActorReminder reminder = GetReminder("reminderRecurring");
            await UnregisterReminderAsync(reminder);
            break;
    }
}
```
**Expected behavior**

Expected that both reminders would be called within 5 minutes

**Additional context**

Running on live environment using Microsoft.ServiceFabric.Actors v3.2.176

**Comment by amanbha** [comment]
@lindgrend Seems like, you have reached out to Microsoft Support team regarding this issue, I will follow up on the incident through the support team. If that's fine, I will close this use.

**Comment by amanbha** [comment]
@lindgrend I have requested Microsoft support team to setup a phone call so that we can go over this and understand your design  as that would be the fastest way as compared to emails, so will resolve it using the support route, will close this issue, please feel free to open this  if you have any further questions.

**Comment by joaocpribeiro** [comment]
@lindgrend @amanbha Could you please let us know whether the reminder was really not being triggered? Thanks.
