### ISSUE TITLE
Feature Request : IConfiguration support for Service Fabric Configuration

### ISSUE THREAD

**Issue by RamjotSingh** [Microsoft/service-fabric-services-and-actors-dotnet#151]
**Is your feature request related to a problem? Please describe.**
ASP.NET Core supports IConfiguration based configuration providers making it easy to bring together configuration from multiple sources.

**Describe the solution you'd like**
Service fabric official solution to access SF configuration using IConfiguration

**Comment by amanbha** [comment]
This is tracked in Service Fabric aspnet core repo https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/issues/151
