### ISSUE TITLE
Custom serialization using wrapped messages results in error

### ISSUE THREAD

**Issue by IvanAlekseev** [Microsoft/service-fabric-services-and-actors-dotnet#152]
**Describe the bug**
Following a [guide](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#upgrade-from-remoting-v1-to-remoting-v2-interface-compatible) on custom serialization in v2 with wrapped messages results with error 
```
[A]NewServiceClient.INewService_.service.mt.GetDtoReqBody cannot be cast to [B]NewServiceClient.INewService_.service.mt.GetDtoReqBody. Type A originates from 'NewServiceClient.INewService_.service.mt, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'LoadNeither' in a byte array. Type B originates from 'NewServiceClient.INewService_.service.mt, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'LoadNeither' in a byte array.
```

INewService is an interface for my service fabric reliable service defined in NewServiceClient project. I am calling service from console app using this code:
```csharp
var proxy = ServiceProxy.Create<INewService>(uri);
var result = await proxy.GetDto(new Dto { Message = "Hello from console" });
```

**To Reproduce**
Following a [guide](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#upgrade-from-remoting-v1-to-remoting-v2-interface-compatible) 

**Expected behavior**
It should work

**Additional context**
Nothing here

**Comment by VipulM-MSFT** [comment]
@IvanAlekseev - would it be possible to share the code?

**Comment by VipulM-MSFT** [comment]
@amanbha / @BharatNarasimman - can you please take a look?

**Comment by VipulM-MSFT** [comment]
@IvanAlekseev  - is the interface defined in more than one assembly by any chance?

**Comment by amanbha** [comment]
@IvanAlekseev  Could you share a sample repo project with your custom serializer and types.

**Comment by suchiagicha** [comment]
@IvanAlekseev 
From your client code snippet , looks like you are not  plugin custom serialization on client side. 
Please check the below code to do the same. and then use below proxy factory to create proxy[ instead of using ServiceProxy.Create which in turn uses default serialization.

var proxyFactory = new ServiceProxyFactory((c) =>
{
    return new FabricTransportServiceRemotingClientFactory(
    serializationProvider: new ServiceRemotingJsonSerializationProvider());
  });

**Comment by amanbha** [comment]
@IvanAlekseev  Did you get a chance to try the changes as suggested above.

**Comment by amanbha** [comment]
@IvanAlekseev I am closing it because of lack of response, please feel free to reopen if you still need help with this.
