### ISSUE TITLE
WCF client/listener on .net core application

### ISSUE THREAD

**Issue by orestisp** [Microsoft/service-fabric-services-and-actors-dotnet#153]
I'm trying to setup a WCF listener on a .net core Actor service and a WCF client on an asp.net core web app. 
 However, WcfActorServiceRemotingListener and WcfActorRemotingClientFactory take in as parameter the System.ServiceModel.Channels.Binding class, which is part of a .NET framework assembly.  Referencing the .NET core version of System.ServiceModel is not working because it has missing fields (Fails during runtime when calling WcfUtility.CreateTcpListenerBinding).

How are we supposed to use the WCF listener and client in .net core applications?

**Comment by amanbha** [comment]
@orestisp  WCF is not supported on .net core.
