### ISSUE TITLE
Custom serialization provider - caching

### ISSUE THREAD

**Issue by orestisp** [Microsoft/service-fabric-services-and-actors-dotnet#154]
Looking at ServiceRemotingMessageSerializersManager.cs, it seems to be caching the created body serializers based on interfaceId.

I'm using a custom serialization provider (IServiceRemotingMessageSerializationProvider) and I get calls to create serializers for every request, even if interfaceId is the same.  Is this expected?  Should I implement caching on the provider?

The stack trace that leads to the creation on every request is:

```
ServiceRemotingMessageSerializersManager.CreateSerializers(int interfaceId)
ConcurrentDictionary<int, CacheEntry>.GetOrAdd(int key, System.Func<int, CacheEntry> valueFactory) Line 989
ServiceRemotingMessageSerializersManager.GetRequestBodySerializer(int interfaceId)
FabricTransport.Client.FabricTransportServiceRemotingClient.RequestResponseAsync(IServiceRemotingRequestMessage remotingRequestRequestMessage)
```

**Comment by VipulM-MSFT** [comment]
The caching is performed at the proxy factory level, if the proxy factor is recreated, it will recreate the serialization manager and hence the serializers.

**Comment by orestisp** [comment]
Thank you.  I mistakenly assumed that the serializes being created was on the server side.  By using a single instance of the proxy factory the serializes are cached as expected.
