### ISSUE TITLE
ASP.NET Core Actor Service 

### ISSUE THREAD

**Issue by orestisp** [Microsoft/service-fabric-services-and-actors-dotnet#162]
When adding a new service fabric service, there are five templates to choose from:
1.  Stateless Service
2.  Stateful Service
3.  Stateless ASP.NET Core Service
4.  Stateful ASP.NET Core Service
5.  Actor Service

Is it possible to add an ASP.NET Core Actor Service?  The use case is to have an actor service that exposes a REST API as an interface to it's actors methods.  If yes, it would be nice to have an example of this, or have it as an option in the template menu.  Currently the alternative is to have another stateless service that acts as a gateway, and calls the actor service through remoting.

**Comment by amanbha** [comment]
@orestisp ASP net core request processing pipeline is different than Actors, For making actor calls you need to determine the partition id to which the request must be routed to, what you mentioned about having an Aspnetcore service calling into an actor service is the best option.
