### ISSUE TITLE
Cannot rename reliable actor service type

### ISSUE THREAD

**Issue by Liversage** [Microsoft/service-fabric-services-and-actors-dotnet#169]
I'm having this issue with Service Fabric SDK 3.3.622 and Visual Studio 15.9.5.

Here are steps to recreate my issue:

- Create a new Service Fabric Application (.NET Framework 4.7.2) in Visual Studio
- Select the .NET Core Actor Service template
- Build the solution
- Debug on a 1 node local cluster and verify that the service works

So far so good. Now I want to make some changes to the boilerplate `ServiceManifest.xml`. Let me rename the service type:

- Edit `Actor1.csproj` and remove `<UpdateServiceFabricManifestEnabled>True</UpdateServiceFabricManifestEnabled>`
- Edit `ServiceManifest.xml` and change the value of the `ServiceTypeName` attribute to `Actor1` (get rid of the `ActorServiceType` suffix which to me is like Hungarian notation)
- Edit `ApplicationManifest.xml` and make the same change so the types match
- Debug on a 1 node local cluster

Now the service cannot start. Instead the following exception is thrown in `Program.Main`:

```
{System.Fabric.FabricException: Invalid Service Type ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80071C21
   at System.Fabric.Interop.NativeRuntime.IFabricRuntime.EndRegisterStatefulServiceFactory(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.Utility.<>c__DisplayClass22_0.<WrapNativeAsyncInvoke>b__0(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   at Microsoft.ServiceFabric.Services.Runtime.ServiceRuntime.RegisterServiceAsync(String serviceTypeName, Func`2 serviceFactory, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Actors.Runtime.ActorRuntime.RegisterActorAsync[TActor](Func`3 actorServiceFactory, TimeSpan timeout, CancellationToken cancellationToken)
   at Actor1.Program.Main() in C:\Users\Martin\Source\Repos\Application1\Actor1\Program.cs:line 24}
```

The message is **Invalid Service Type** so there must be some hard coded naming convention in the reliable actor framework. I have tried to play around with modifications of the names in `ServiceManifest.xml` but most of the time the service cannot start. The exception can be the above about the invalid service type or a missing configuration section (they also seem to be hardcoded even though they are in `ServiceManifest.xml`).

While this is not a serious problem because I can just use the boilerplate XML I have not found any [documentation of the XML in `ServiceManifest.xml`](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources) and I don't like that it appears to be a file I control when in reality even a simple change can break my service.

One thing I did manage was to rename the actor service. This seems to work if the service name (the `Name` attribute of the `Service` element in `ApplicationManifest.xml`) matches the `Name` attribute of the `DefaultService` element in `ServiceManifest.xml`. I haven't been able to find any documentation of this but I was able to guess this dependency myself.

While I wanted to use a clear problem statement as the title of this issue it is really about _what is going with reliable actors and `ServiceManifest.xml`? It's so fragile and I didn't fine a single line of documentation!_ Please let me configure my service and don't trip me up by having hardcoded dependencies on names.

**Comment by Liversage** [comment]
I just tried to rename my actor type which immediately broke my service. It seems that this hidden name dependency is between the name of the actor type and the "magic" names used in `ServiceManifest.xml`.

I could of course turn on the automatic updating of the manifests but 1) I lose all control over names including the service name and 2) to me it is a very jarring experience that source files I edit to configure my system are updated by a tool when I least expect it. Code generation where the generator owns the file is fine as opposed to a code generator that updates my files in ways I don't expect.

At least I now have a better understanding of how to get things working again and my mental model of how actors are implemented in Service Fabric improves. Before, it didn't occur to me that I have to create a service type for each actor type. A sample the shows how to have more than one actor type would be nice to study.

**Comment by amanbha** [comment]
Yes, there is a correlation between the names generated in the manifests and name used by Actor runtime for various settings. Please don't remove UpdateServiceFabricManifestEnabled from the .csproj. There is a utility which runs during the build to update manifests with correct names.

**Comment by FDUdannychen** [comment]
Can we rename the service now? I got similar issues when renaming a service.
