### ISSUE TITLE
DeleteActorAsync doesn't delete the Actor

### ISSUE THREAD

**Issue by niranjanbohra** [Microsoft/service-fabric-services-and-actors-dotnet#173]
**Describe the bug**
We create the Actor with custom json serialize

        public IItemActorService GetActor(string organizationId, string actorId)
        {
            var actorProxyFactory = new CustomActorProxyFactory(serializationProvider: new ServiceRemotingJsonSerializationProvider());
            return actorProxyFactory.CreateActorProxy<IItemActorService>(new Uri(LiveWorkItemActorConstants.ServiceURI), new ActorId($"{organizationId.ToLower()}_{actorId.ToLower()}"));
        }
 
Our delete function:
        public async System.Threading.Tasks.Task DeleteActorAsync(string organizationId, string serviceActorId)
        {
            var actorToDelete = new ActorId($"{organizationId.ToLower()}_{serviceActorId.ToLower()}");
            var myActorServiceProxy = ActorServiceProxy.Create(new Uri(LiveWorkItemActorConstants.ServiceURI), actorToDelete);
            await myActorServiceProxy.DeleteActorAsync(actorToDelete, new CancellationToken()).ConfigureAwait(false);
        }

Registering the Actor service: 

                ActorRuntime.RegisterActorAsync<LiveWorkItemActorService>(
                   (context, actorType) => new CustomActorService(context, actorType, serializationProvider: new ServiceRemotingJsonSerializationProvider(), settings: new ActorServiceSettings() {
                   ActorGarbageCollectionSettings = new ActorGarbageCollectionSettings(200, 200)
                   })).GetAwaiter().GetResult();

We delete a actor and make a call again to actor to see if actor is getting created or using existing instance.

**Comment by amanbha** [comment]
@niranjanbohra Could you explain in more detail, is the actor not getting deleted? How is that determined?

**Comment by niranjanbohra** [comment]
When we call a method of actor first time when actor was not created, It create a instance of actor, Means it hit the constructor of Actor. But next call on-wards it doesn't hit the constructor of actor as instance is already created so it just hit the method. So we are deleting the actor and then calling a method on it, and that time it doesn't hit the constructor it just call the method directory, means the instance was already there.

**Comment by amanbha** [comment]
@niranjanbohra How far apart are delete calls and the second call after that. Are these both calls made from the same client code one after another, or these calls are made from different clients? If from different clients, the calls can get executed on server in any order. Basically we want to understand how did you determine that the actor was actually deleted?

**Comment by niranjanbohra** [comment]
This is how we delete Actor instance and it throws datacontract serialize.  We didn't get a way to create ActorServiceProxy with custom serialize.  
            var actorToDelete = new ActorId($"{organizationId}_{serviceActorId}");
            var myActorServiceProxy = ActorServiceProxy.Create(new Uri(LiveWorkItemActorConstants.ServiceURI), actorToDelete);
            myActorServiceProxy.DeleteActorAsync(actorToDelete, CancellationToken.None);
Exception: 

System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract) at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns) at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver) at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver) at Microsoft.ServiceFabric.Services.Common.SerializationUtility.Deserialize(DataContractSerializer serializer, Byte[] buffer) at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Microsoft.Crm.OmniChannel.LiveWorkItemActorService.Client.LiveWorkItemActorClientImpl.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.Crm.OmniChannel.LiveWorkItemActorService.Client.LiveWorkItemActorClient.DeleteActor(String organizationId, String serviceActorId) at Microsoft.Crm.OmniChannel.RoutingActorService.EventProcessing.Processors.ChannelConnector.ChannelConnectorChatInitEventProcessor.d__7.MoveNext() in F:\CRM.OmniChannel.Routing\src\RoutingActorService\EventProcessing\Processors\ChannelConnector\ChatInitEventProcessor.cs:line 90

**Comment by niranjanbohra** [comment]
Inner Exception :
"Unable to find a constructor to use for type Microsoft.ServiceFabric.Actors.ActorId. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'value.actorId.Kind', line 1, position 408."}	System.Exception {Newtonsoft.Json.JsonSerializationException

at Microsoft.ServiceFabric.Services.Communication.Client.ServicePartitionClient`1.d__24`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.V2.Client.ServiceRemotingPartitionClient.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ServiceFabric.Services.Remoting.Builder.ProxyBase.d__21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Microsoft.Crm.OmniChannel.LiveWorkItemActorService.Client.LiveWorkItemActorClientImpl.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Microsoft.Crm.OmniChannel.LiveWorkItemActorService.Client.LiveWorkItemActorClient.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Microsoft.Crm.OmniChannel.RoutingService.RoutingService.d__4.MoveNext() in F:\CRM.OmniChannel.Routing\src\RoutingService\RoutingService.cs:line 125

**Comment by amanbha** [comment]
@niranjanbohra You can create a proxy with custom serializer as follows:
```
var serviceProxyFactory = new ServiceProxyFactory((c) =>
                    {
                        return new FabricTransportServiceRemotingClientFactory(serializationProvider: new ServiceRemotingJsonSerializationProvider());
                    });

                    var partitionKey = new ServicePartitionKey(actorId.GetPartitionKey());
                    var serviceProxy = serviceProxyFactory.CreateServiceProxy<IActorService>(new Uri("fabric:/Application7/Actor1ActorService"), partitionKey);

                    serviceProxy.DeleteActorAsync(actorId, CancellationToken.None).Wait();
```

It looks like you are using Newtonsoft, so you will have to rely on custom converter for it which handles ActorId.

**Comment by amanbha** [comment]
@niranjanbohra Please let me know if further help is needed for this issue else I will close the issue by end of this wiik.
