### ISSUE TITLE
ServicePartitionClient is not aware of the ports changed if a node is restarted

### ISSUE THREAD

**Issue by ajaykaluraItron** [Microsoft/service-fabric-services-and-actors-dotnet#176]
We have three node cluster which has 18 micro services. While creating the cluster, we have given the a range of dynamic ports that can be assigned to the WEB Api hosted in the cluster. Suppose, initially, node v1 has "X" service hosted in 2000 port and node v2 has "Y" service hosted in 2002 port. Now, node v2 is restarted, after restarting port of "Y" service is changed in the node V2 to 2003.

When a request is sent from V1 "X" service to V2 "Y" service, the ServicePartitionClient is calling the "Y" service with the old port only. The ServicePartitionClient does not know about that port changed to 2003.

Following code is used:

 using (var factory = new HttpCommunicationClientFactory(new ServicePartitionResolver(() => _fabricClient), null, _logger, _utilityHelper))
            {
                var partitionClient = new ServicePartitionClient<HttpCommunicationClient>(factory, serviceUri, null, TargetReplicaSelector.Default, null, _retrySettings);
                HttpResponseMessage response = null;
                string fullUrl = string.Empty;
                await partitionClient.InvokeWithRetryAsync(
                                   async (client) =>
                                   {
                                       CommonMethods.ConstructHeader(tenantId, client);                                       
                                       UriBuilder builder = new UriBuilder(client.Url);
                                       fullUrl = builder.ToString();
                                       response = await httpAsyncAction(client.HttpClient, Path.Combine(fullUrl, apiPath), payload == null ? null : new StringContent(payload, Encoding.UTF8, _jsonMediaType));
                                   });

                string content = await response.Content.ReadAsStringAsync();

                if (!response.IsSuccessStatusCode)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized)
                    {
                        throw new UnauthorizedAccessException("Unauthorized");
                    }
                    else if (response.StatusCode == HttpStatusCode.BadRequest)
                    {
                        var exception = JsonConvert.DeserializeObject<JObject>(content);
                        JToken value;
                        if(exception.TryGetValue("message", out value))
                        {
                            var message = value.ToString();
                            throw new ArgumentException(message);
                        }
                        throw new ArgumentException(content);
                    }
                    else if (response.StatusCode == HttpStatusCode.NotFound)
                    {
                        _logger.Log(content, System.Diagnostics.Tracing.EventLevel.Error);
                        throw new KeyNotFoundException("Not found");
                    }
                    else
                    {
                        throw new Exception(string.Format("Error - Unable to perform HTTP request to url {0}. Status code: {1} Error message: {2}", fullUrl,
                            response.StatusCode, content ?? string.Empty));
                    }
                }
                else
                {
                    return response;
                }
            }

Also,HttpCommunicationClientFactory  is inherted from CommunicationClientFactoryBase class. We have also added an IExceptionHandler in the constructor of HttpCommunicationClientFactory  so that retry should occur but even the retry not happening. 

HttpCommunicationClientFactory : CommunicationClientFactoryBase<HttpCommunicationClient>, IDisposable

Any feeback is appreciated. We are using 5.3.301 Microsoft.ServiceFabric nuget

**Comment by amanbha** [comment]
@ajaykaluraItron  What is the nuget package version for Microsfot.ServiceFabric.Services used by your project. 5.3 for Microsoft.ServiceFabric is very old and out of support, could you please upgrade to latest versions

**Comment by amanbha** [comment]
@ajaykaluraItron  closing this due to lack of response, please feel free to reopen if further help is needed.
