### ISSUE TITLE
Build fails when UpdateServiceFabricManifestEnabled is set to true for framework dependent FDD or FDE

### ISSUE THREAD

**Issue by narcis-pv** [microsoft/service-fabric-services-and-actors-dotnet#194]
**Describe the bug**
Build fails if you try to build with `<SelfContained>True</SelfContained>` in csproj or if you remove the `<RuntimeIndentifier>`. Basically if you try to build a framework dependent project.

**To Reproduce**

1. Create new Service Fabric Actors project
2. Edit csproj, remove `RuntimeIndentifier` **or**  add `<SelfContained>false</SelfContained>`
3. Build

**Expected behavior**
Build should be successful.

**Actual behavior**
Build fails withe following error: 
```
The command "dotnet "obj\\FabActUtilTemp\FabActUtil.dll" /spp:"PackageRoot" /t:manifest /sp:"Actor1" /in:"bin\Debug\netcoreapp2.2\win7-x64\\Actor1.dll" /arp:"C:\Users\%username%\source\repos\Application1\Actor1\bin\Debug\netcoreapp2.2\win7-x64\\" " exited with code -2147450745.
Actor1
C:\Users\%username%\.nuget\packages\microsoft.servicefabric.actors\3.3.654\build\netcoreapp2.0\Microsoft.ServiceFabric.Actors.targets
22
```

**Environment context**
`dotnet --info` output
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by narcis-pv** [comment]
Apparently one workaround is described by @kentcb and @amanbha in [here](https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/issues/150).

`TL;DR;` You can disabled this option if you have built at least once and the config is generated.

**Comment by amanbha** [comment]
@anantshankar17 I believe this scenarios will be fixed by your PR https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/pull/187 . Please confirm.

**Comment by anantshankar17** [comment]
I'm confused, you seem to be trying to build an FDD project and still trying to enable self contained packaging ? Fundamentally, packaging should be either FDD or SelfContained. VS projects by default are all self contained, for an FDD all you got to do is:
1. remove the RuntimeIdentifier
2. add:  
<Platform>x64</Platform>
<Platforms>x64</Platforms>

**Comment by narcis-pv** [comment]
@anantshankar17 I'm sorry, I've updated the body, it should have `<SelfContained>False</SelfContained>` Thanks for noticing it.

**Comment by anantshankar17** [comment]
@narcis-pv ok, can you try the above mentioned steps instead and see if it builds for FDD ?

**Comment by narcis-pv** [comment]
Same error

![image](https://user-images.githubusercontent.com/45754576/56428917-bff58d00-62c9-11e9-8eac-e18449cf4cee.png)

I have even tried with `<SelfContained>false</SelfContained>`not commented out.

**Comment by anantshankar17** [comment]
Yes, this was fixed in the PR: https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/pull/180.

**Comment by narcis-pv** [comment]
I'm using ` <PackageReference Include="Microsoft.ServiceFabric.Actors" Version="3.3.654" />` latest. When will the PR hit the release?

**Comment by amanbha** [comment]
The fixes addressing this will be part of 3.4.* release. ETA is 3-4 weeks. Till then you can sue the workaround as you mentioned above.

**Comment by MarkDeVerno** [comment]
This issue is marked closed, but it still seems to be an issue when doing a publish with --self-contained=False.  The workaround of setting UpdateServiceFabricManifestEnabled=False for Actors seems to work.

`dotnet publish MyProj.sfproj -c Release -p:PublishSingleFile=true -r win7-x64 --self-contained=false -t:Package`

**Comment by amanbha** [comment]
@anantshankar17 @dbreshears  Could you please take a look at this?

**Comment by anantshankar17** [comment]
@MarkDeVerno I tried doing that on a .netCore3 runtime (since the official version is already release) and works fine for me:
1. I deleted the service manifest, so that publish would regenerate it.
2. Please note, for a FDD (not selfcontained) you need these:
   Remove:     
   Add: 
    <Platform>x64</Platform>
    <Platforms>x64</Platforms>

![image](https://user-images.githubusercontent.com/39825466/68016562-d9d14d00-fcba-11e9-822a-a92cd9bc98a9.png)

Can you please update to .NetCore-3.0 officially release version ?

**Comment by MarkDeVerno** [comment]
@anantshankar17 I followed all the steps, and while it didn't error out, it also didn't produce the /pkg folder.  I'll stick to my workaround by setting updateServiceFabricManifestEnabled=False.
Note: This was with the official version
