### ISSUE TITLE
Data clean up on deactivate

### ISSUE THREAD

**Issue by niranjanbohra** [microsoft/service-fabric-services-and-actors-dotnet#205]
As garbage collection of deactivated actors only cleans up the actor object, but it does not remove data that is stored in an actor's State Manager.  A remote caller needs to call explicitly deleteActorAsync which is overhead at the client side. 

If there is a way to get deleteActorAsync behavior in the deactivated event, it can remove the extra unwanted burden on the client who doesn't want to track Actor.

**Comment by amanbha** [comment]
@niranjanbohra  the actor state is removed form the StateManager on Actor deactivation, the state however is not removed form underlying state provider on deactivation. The state is available to actor again for use when actor is activated again.
If you just want o remove the state stored by the actor, you can remove the state in an overridden OnDeactivateAsync in your actor. For each actor however a small metadata that it was created is also stored in state provider and this will not be removed until you explicitly delete the actor.

**Comment by amanbha** [comment]
Please feel free to activate if more help is needed.

**Comment by sarah-sterchele** [comment]
Can someone explain why it is using Lowkey and the reasoning behind building the partition key?

**Comment by amanbha** [comment]
Actor services in Service fabric are stateful Partitioned Services with [range partitioning](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-concepts-partitioning#ranged-partitioning-scheme). Each partition servers request for a partition key which falls within its lowkey-highkey range.
Its using partition keys for each partition key to reach the target partition.

**Comment by sarah-sterchele** [comment]
Thanks for the fast reply! Your reply makes sense, but I wonder if I am missing a point - why do we we use the lowkey (vs high key, for example).

**Comment by amanbha** [comment]
> Thanks for the fast reply! Your reply makes sense, but I wonder if I am missing a point - why do we use the lowkey (vs high key, for example).

It could have used the high key as well, it just needed a key for the partition range.
