### ISSUE TITLE
Service Fabric Remoting

### ISSUE THREAD

**Issue by nkorai** [microsoft/service-fabric-services-and-actors-dotnet#210]
**Describe the bug**
Service remoting worked fine till about 2 weeks ago. Currently works fine on our production cluster, QA cluster as well as other local machines. On my machine I get service remoting timeouts for pretty much every call. I haven't been able to diagnose anything specific so this is a hail mary effort. It doesn't seem like it's specifically Service Fabric, as I see a lot of SocketExceptions when I attach to the service. Something of note is that for every remoting attempt locally I see a log in the Event Viewer under Microsoft-Service-Fabric > Admin that says: 

`NetworkProbe: WinsockNetworkPing connect to server failed. Error: 10051, Address: MyMachineName:19001`

I haven't found anything service fabric related to this particular issue and very little non-service fabric stuff as well, with the most documentation I've found on it being simply that the destination trying to be reached is unreachable.

**To Reproduce**
Unable to reproduce.

**Expected behavior**
Service remoting should work.

**Comment by nkorai** [comment]
Closing any apps that use the internet seems to allows the remoting calls to start working again. Pretty confused by this, can't think why this is suddenly an issue when it's always worked in the past

**Comment by amanbha** [comment]
@nkorai This doesn't seem related to SF or remoting, it seems something on your machine.

**Comment by nkorai** [comment]
That's fair but I'm worried that this problem will eventually show up in our production cluster. It seems like a network resources/port exhaustion issue. Every other app continues to work on my machine but only Service Fabric stops working with the stated Event Log error. Another colleague has also seen this occur on their machine.

**Comment by amanbha** [comment]
@nkorai could you use netstat to see who is using the ports.

**Comment by davebally** [comment]
Any update on this issue ? We are experiencing the same error "NetworkProbe: WinsockNetworkPing connect to server failed. Error: 10051".  This is on a 3 node dev cluster on AWS EC2 instances.  All nodes have issues talking to all other nodes on ports 19001 and 19002.  Service fabric explorer is not reporting issues, we are able to upgrade services etc just fine.  No other symptoms noticed, we dont use remoting,  but cross node service-2-service calls are fine.   Have bounced all the servers to confirm no ie etc running.

**Comment by amanbha** [comment]
@davebally This doesn't seem related to SF or remoting, it seems something on your EC2  machine..   could you use netstat to see who is using the ports.

**Comment by davebally** [comment]
Hi @amanbha ,  here is snippets from the netstat from both node-0 and node-2 that are having problems talking to each other on 19001 and 19002.
As you can see getting " Can not obtain ownership information" on those ports,  should this be fabric.exe.   Its not on my dev laptop.. ???
There is showing at least 1 established connection too.



```
sf-node-0  IP = 10.140.78.90

 TCP    0.0.0.0:19000          0.0.0.0:0              LISTENING       3860
 [FabricGateway.exe]
  TCP    0.0.0.0:19001          0.0.0.0:0              LISTENING       2864
 [Fabric.exe]
  TCP    0.0.0.0:19002          0.0.0.0:0              LISTENING       4
 Can not obtain ownership information
  TCP    0.0.0.0:19080          0.0.0.0:0              LISTENING       4
 Can not obtain ownership information
  TCP    0.0.0.0:19081          0.0.0.0:0              LISTENING       4
 
 TCP    10.140.78.90:49831     10.140.78.19:19002     ESTABLISHED     4
 Can not obtain ownership information

sf-node-2 ip= 10.140.78.19

 TCP    0.0.0.0:19000          0.0.0.0:0              LISTENING       6132
 [FabricGateway.exe]
  TCP    0.0.0.0:19001          0.0.0.0:0              LISTENING       2052
 [Fabric.exe]
  TCP    0.0.0.0:19002          0.0.0.0:0              LISTENING       4
 Can not obtain ownership information
  TCP    0.0.0.0:19080          0.0.0.0:0              LISTENING       4
 Can not obtain ownership information
  TCP    0.0.0.0:19081          0.0.0.0:0              LISTENING       4
  
  
  TCP    10.140.78.19:19002     10.140.78.90:49831     ESTABLISHED     4
 Can not obtain ownership information
  TCP    10.140.78.19:19002     10.140.78.133:49822    ESTABLISHED     4
 Can not obtain ownership information
 ```

**Comment by amanbha** [comment]
@davebally This looks like a machine specific issue, I am not familiar with how VMs are configured in EC2. It would need more investigation, could you please open a support ticket with Microsoft to get help with this: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support

**Comment by aL3891** [comment]
i've also seen this issue on atleast four diffrent machines.. i dont think you can pin this on some machine specific issue. for us it seems to be specific to fabric version  6.4.658.9590, when i installed 6.4.664 on one of them the timeouts seems to stop.

**Comment by amanbha** [comment]
@aL3891  please open a support ticket with Microsoft to get help with this: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support
