### ISSUE TITLE
Un-/Reliable UDP Actor Communication

### ISSUE THREAD

**Issue by KDSBest** [microsoft/service-fabric-services-and-actors-dotnet#212]
**Is your feature request related to a problem? Please describe.**
I want to save fast changing values in volatile Actor state and use the actor model to distribute calculation on the state.
For example: I have an MMO with information the client controls. The client sends updates of playerposition to his own actor. The actor does some calculation and validation, but speed is most important. If some playerpositions are lost because of networking then they are ignored.

**Describe the solution you'd like**
I would love to have a lightweight Reliable UDP Networking Layer and be able to mark methods as [Unreliable].

**Describe alternatives you've considered**
Having a service with an udp listener, which relays the messages to an actor. This solves most issues due to bad client networking, but internal communication can still be bad.

**Additional context**
I will fork the repo and start working on it myself. Maybe there is a better way.

**Comment by amanbha** [comment]
@KDSBest 
You can plugin your own transport using the V2 remoting layer.

You need to implement the following classes  using your transport code .
(IServiceRemotingClientFactory)[https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.remoting.v2.client.iserviceremotingclientfactory?view=azure-dotnet]
IServiceRemotingCallbackMessageHandler
IserviceRemotingListener

We have a  public Actor  dispatcher  class to dispatch this in your  listener implementation which provides turns based concurrency. 

Here is one similar example for WCF we provide.
Corresponding CLientFactory , Listener
This is a sample on how to inject the above class in the actor framework.
