### ISSUE TITLE
The api IStatelessServiceInstance.Close on node XXX is stuck

### ISSUE THREAD

**Issue by danny156** [microsoft/service-fabric-services-and-actors-dotnet#220]
From time to time, when our application is being upgraded, we get the following warning:
Message: [HealthState: Warning: 100% (1/1) partitions are unhealthy. The evaluation tolerates 0% unhealthy partitions per service.
HealthState: Warning: Partition '780986b6-d226-4806-a0b5-41ed314825e5' is in Warning.
HealthState: Warning: 100% (1/1) replicas are unhealthy. The evaluation tolerates 0% unhealthy replicas per partition.
HealthState: Warning: Replica '132104847929797869' is in Warning.
HealthState: Warning: 'System.RAP' reported Warning for property 'IStatelessServiceInstance.CloseDuration'.
The api IStatelessServiceInstance.Close on node XXX is stuck. Start Time (UTC): 2019-08-17 21:48:31.871.]

Need to mention that it definitely not a cancellation token issue, as our RunAsync method returns immediately.

So, we thought it might be related to our service listeners. Since it has more than ~30 listeners, I changed the timeout property of the binding (WCF) to 5 seconds instead of default 1 minute.

In addition, I have added event handlers to log whenever a listener is moving to its closed/closing states.
Inspecting the logs, I see that the SF run time hangs during the close.
Here is an example:
AAAService Closing at 8/17/2019 9:48:31 PM	
AAAService Closed at: 8/17/2019 9:48:31 PM		
**What HAPPENED HERE ?? **
BBBService Closing at 8/17/2019 9:53:37 PM		
CCCService Closing at 8/17/2019 9:53:37 PM 	
...

So, no wonder we get the warning. The only question is what was happening after the AAAService listener was closed ?

**Comment by amanbha** [comment]
This would need looking at your cluster traces. If it's a production cluster, please open a support ticket with Microsoft support: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-support#report-production-issues-or-request-paid-support-for-azure

**Comment by danny156** [comment]
How can I access to cluster traces ?

**Comment by amanbha** [comment]
@danny156 When creating the cluster you can configure the cluster to upload traces to a file share or to azure storage. Traces from nodes are pushed to that. If you open support ticket, support team can help with that information.

**Comment by danny156** [comment]
@amanbha Thanks, will check it.
Other then that, no idea what could be wrong ?

**Comment by amanbha** [comment]
@danny156 you can take the dump of the process and analyze what's causing it to stuck.

**Comment by esbenbach** [comment]
@danny156  we previously had the same thing, and after quite a bit of back and forth with support, it turned out to be related to the way we registered Application Insights during startup. It would end up not honouring the cancellation request, in a few cases it would eventually "die", but that "eventually" could take hours.

I would suggest you push support a bit, they should be able to help you pinpoint the issue :)

**Comment by danny156** [comment]
@esbenbach  As we have reduced the amount of listeners, this error now appears from 1/1 to ~1/8.
So, is it possible SF can't handle large amount of listeners ?
We currently have ~30.

**Comment by esbenbach** [comment]
Maybe, though that does seem a bit weird, as long as all the listeners honour the cancellation request and terminates then i dont think it should be a problem.

**Comment by danny156** [comment]
I agree, but look at the ratio change once we have removed some listeners.

**Comment by esbenbach** [comment]
Yearh it seems odd, an i know nothing of which type of listeners you have - so it may just be the amount of listeners. Are they all similar? If so I would try just creating a dummy service with a 30+ "dummy" listeners to see if that can be upgraded or not....

**Comment by danny156** [comment]
It is possible, but I am guessing we are missing something, and this is not just the amount of listeners as you mentioned.

**Comment by amanbha** [comment]
Please reopen if you have further questions or need help

**Comment by Sashwat** [comment]
> @danny156 we previously had the same thing, and after quite a bit of back and forth with support, it turned out to be related to the way we registered Application Insights during startup. It would end up not honouring the cancellation request, in a few cases it would eventually "die", but that "eventually" could take hours.
> 
> I would suggest you push support a bit, they should be able to help you pinpoint the issue :)

Canyou tell more about this? What is the right way to register app insights
