### ISSUE TITLE
ReliableDictionary2 Cannot add items after initial commit of ITransaction, in subsequent transactions

### ISSUE THREAD

**Issue by TKocoloski** [microsoft/service-fabric-services-and-actors-dotnet#229]
**Describe the bug**
A clear and concise description of what the bug is
If using a complex type for the key that implements IComparable<T> and IEquatable<T> than adding additional items after commit will silently fail.

**To Reproduce**

1 ) Create a struct that implements both interfaces
2) Create a transaction 
3) Add two items to the dictionary with different key values
4) Commit the transaction
5) Open a new transaction and attempt to add a third item and commit transaction.  The count will remain at two.
6) Enumerate through the dictionary and observe only the first two items are present

**Expected behavior**
I would expect to be able to add items to the dictionary more than one time.

**Additional context**

**Comment by amanbha** [comment]
@TKocoloski This repo is for SF aCtors and Services layer and doesnt cover ReliableCollections, for ReliableCollections could you please open issue in the main SF repo at https://github.com/Microsoft/service-fabric/issues
