### ISSUE TITLE
V1 Remoting method name

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [microsoft/service-fabric-services-and-actors-dotnet#236]
MethodId is present in the `ServiceRemotingMessageHeaders` headers with V1 of Remoting (net) but not the method name like in V2.  Anyway to hack out the name in V1?

**Comment by amanbha** [comment]
Please see this https://dev.to/expecho/service-fabric-remoting-interception--custom-headers--3800

**Comment by MatthewDavidCampbell** [comment]
@amanbha Thanks for the link.  We do something similar (i.e. pipelines in Service Fabric).

Maybe I should have posed the original question as "any way to translate the Method Id in V1 into a Method Name"?

**Comment by amanbha** [comment]
@MatthewDavidCampbell it won't be possible to translate method id to method name in V1 unless you insert it in the custom headers
