### ISSUE TITLE
Logic error in CreateServiceRemotingInstanceListeners?

### ISSUE THREAD

**Issue by JohnNilsson** [microsoft/service-fabric-services-and-actors-dotnet#237]
In [this line in CreateServiceRemotingReplicaListeners](https://github.com/microsoft/service-fabric-services-and-actors-dotnet/blob/973c709bb5981c27b6b19166cb158b4e77a8a885/src/Microsoft.ServiceFabric.Services.Remoting/Runtime/ServiceRemotingExtensions.cs#L93) there is double if-check against `provider.RemotingListenerVersion` should one of those checks have been against `provider.RemotingClientVersion` instead?

**Comment by abatishchev** [comment]
I'd suggest to submit a simple pull request and ping @BharatNarasimman on it.
