### ISSUE TITLE
Actor Service not releasing threads

### ISSUE THREAD

**Issue by nforysinski** [microsoft/service-fabric-services-and-actors-dotnet#245]
**Describe the bug**
I have an actor service running in a 10-node cluster on an Azure VM scale set. There are 4 total actor types in the service, some of which are long-running and reused, some are not re-used and immediately deleted, and some are not re-used but cleaned out nightly from an external process.

The application works by an exterior process creating an actor, who executes some complicated I/O logic, and then either calls a re-usable actor to do some work, or calls another actor to do some work and immediately deletes said actor. The top level actor uses a set of reminders that are unset when he is done. We do see proper actor deactivation in all cases, so we know its not any set of actors staying active for too long.

After observing the VM resources in production for some time we see that the actor service has amassed a very large number of threads and does not seem to release them. After 24 hours of processing around 50-100 requests per second at the top actor, there are roughly 7,000 threads on some of the nodes. Over a course of days this can grow to 15,000+ threads and eventually this seems starts to starve the thread pool or otherwise cause degraded performance to the point of network calls taking too long to respond, actors not processing new requests quickly, and the cluster seems to be struggling to rebalance which causes high disk activity.

We have done several revamps to our code base to reduce dependencies, ensure better unit-of-work constraints and that all injected dependencies are cleaned up, and limited state use to the very minimum. All have helped with individual request performance, but overall the actor service seems to continue to amass threads.

Other actor services running much less intensive operations but utilizing many of the same dependencies do not exhibit this behavior. We also don't see this behavior on our 3-node development cluster or our local environments. As far as we can see, threads are being readily cleared up on those environments.

Could it be a set of open connections that aren't being closed with actor deactivation? How can we go about debugging where threads are being generated and why they arent being released?

**Additional context**
Using AutoFac for dependency injection - all per request dependencies are initiated in a child scope thats immediately disposed, any other dependency is a singleton
Azure SQL database with Azure Redis as a cache layer
HttpClient is a singleton where used

**Comment by amanbha** [comment]
@nforysinski Increase in thread count, usually points to mixing of sync code with async code. Please review the code to see code where you are doing .Wait(), .GetAwiater().GetResult(), or libararies which you are using and they have sync code. You can capture the dump and analyze the dump to see what the threads are doing?

**Comment by nforysinski** [comment]
@amanbha Thanks for the input. After getting some crash dumps, we traced the issue to Application Insights which had its configuration being created with each new Actor. This is an anti-pattern but not a well-documented one as there is sparse documentation for how to integrate AI into actor services.

The key takeaway for us was to create a single TelemetryConfiguration in Program.cs where the actor services are created. That configuration is then shared through the rest of the actors.

**Comment by amanbha** [comment]
@nforysinski That's great, yes creating certain resources at ActorService level and using them in Actor instances is the correct approach.
