### ISSUE TITLE
Customizable IActorTimers

### ISSUE THREAD

**Issue by Jm-Fox** [Microsoft/service-fabric-services-and-actors-dotnet#35]
IActorTimer provides a nice abstraction over timers, but it is not customizable. ActorBase always uses the internal implementation ActorTimer:
https://github.com/Azure/service-fabric-services-and-actors-dotnet/blob/master/src/Microsoft.ServiceFabric.Actors/Runtime/ActorBase.cs#L274

There should be an overload which roughly does the same thing:
```
protected void RegisterTimer(IActorTimer timer)
{   
    if (this.GcHandler.IsGarbageCollected)
    {
        throw new ObjectDisposedException("actor");
    }

    if (this.timers == null)
    {
        this.timers = new List<IActorTimer>();
    }
	
    this.timers.Add(timer);
}
```

This issue is very important to me because System.Threading.Timer does not perform well at high frequencies, which I require for a game loop. Testing on my (weak) desktop indicates that under no circumstances can Timers ever reach 60 FPS with callbacks (seems to cap out at 42 FPS). Meanwhile using Monitor.Wait() or Thread.Sleep() allow me to keep 60 FPS on hundreds of simluated game loops.
My desktop processor is not nearly as powerful or good at multithreading as the processors my servers will have, but the performance difference is too large to discount.

Update: formatted code

**Comment by VipulM-MSFT** [comment]
@Jm-Fox - Definitely this is something that can be customizable. Would it be possible for you to suggest the fix and a PR for the issue?

**Comment by Jm-Fox** [comment]
Yes, I've forked the repo and created pull request #36.

**Comment by vturecek** [comment]
@Jm-Fox thanks! Looks pretty good to me.
@harahma can you review real quick and merge if it looks good to you?

**Comment by Jm-Fox** [comment]
I'm not attached to any implementations, I'll probably make several and use whichever turns out to have the best performance. I'll try both Monitor.Wait() and Thread.Sleep(), though I'm not fond of either of those.

**Comment by amanbha** [comment]
PR #36

**Comment by amanbha** [comment]
@harahma please look at pull request #36 for this.

**Comment by VipulM-MSFT** [comment]
@Jm-Fox - do you still need this feature? @amanbha - can the PR be modified to provide the needed enhancement without sacrificing the turn based concurrency?

**Comment by Jm-Fox** [comment]
Actually, no, I don't still need this feature. I'll go down one of the two following paths:

1. Implement my game loop critical code in a partitioned StatefulService instead of an Actor
2. Implement game loop evaluation lazily instead of proactively. So instead of calculating the state at 60hz, run simulations for .5 seconds if no method was called for .5 seconds.

Currently I'm leaning towards (1), but either way I don't need to extend IActorTimer.

**Comment by amanbha** [comment]
Thanks for confirming @Jim-Fox, I will close this issue as the PR has already been closed.
