### ISSUE TITLE
FeatureRequest: Consider adding a StateManage (or StateProvider) at ActorService level.

### ISSUE THREAD

**Issue by grahamehorner** [Microsoft/service-fabric-services-and-actors-dotnet#48]
please consider allowing the actor state manager to be used by other developers from within custom ActorServices for example

**Comment by amanbha** [comment]
StateManager is for the Actor, what is exposed at Actor service layer is StateProvider. Do you have any scenario in mind which can't be accomplished by using StateProvider at Actor service layer.

**Comment by amanbha** [comment]
@vturecek for feature request.

**Comment by VipulM-MSFT** [comment]
@grahamehorner - is this feature still required or where you able to make your scenario work. Apologies for the significantly large delay in the response. We are prioritizing some of the work and wanted to know if we can consider this now.

**Comment by amanbha** [comment]
@grahamehorner I am closing this issue, please reopen if this feature is still required. Please provide the scenario, which can't be accomplished by using StateProvider at Actor service layer.

**Comment by AdamPliska** [comment]
It’d be nice to be able to map ActorId with a real world AssetId, for example, say I am using the actor pattern for an IOT solution. Each actor corresponds to a real world IOT device. The devices are indexed, Device1, Device2, Device3, Device4, etc. to insure an even distribution of the AssetId I’d use AssetId.CreateRandom, and then store the corresponding Device (Device1 for example) with the randomly created AssetId. I could then write a service in the Actor Service Layer that does the lookup and provides an interface to convert a “deviceId” into an “ActorId”.
I could use a reliable dictionary to store these lookups, right? I do not seem to have access to those via the StateProvider, as I would with the StateManager.
