### ISSUE TITLE
Support for serverless computing

### ISSUE THREAD

**Issue by prapicault** [Microsoft/service-fabric-services-and-actors-dotnet#58]
I've been experimenting with service fabric for the last couple months and I'm really big fan, especially of the actor model.
However there are a number of situations (e.g. writing one-off tasks, administrative tasks, etc.) where having to write a stateless service and deploy it (including all the steps required for this) is just a little bit too cumbersome, and having to resort to use Azure Function is not the right granularity (e.g. my sf cluster has credentials, and configuration information that I would not want to have to put somewhere else).

So my question enhancement request is to add a serverless computing capability to sf. At first it would not have to auto-scale, or be as fancy as azure function (e.g. triggers). It could simply start by providing the ability to execute code and this would be nice. For example, one could upload a JS file, an exe, a docker container.

**Comment by amanbha** [comment]
@VipulM-MSFT and @vturecek for insights into this.

**Comment by guibirow** [comment]
Cool idea, I have thought on something similar, where we could have administrative tasks running at intervals and shutdown once completed. Like scheduled tasks, backups, and so on. 
Today we can use the actors, but for this we need a service running all the time.
If we had the concept o 0 instances service we could achieve something similar, but the idea of functions is also valid.

**Comment by bklooste** [comment]
This should be in a separate rep library ..   

- As guibirow alluded to what your after is just a service that runs exe  , eg upload the exe , and process exec it...
- Could also use Roslyn to  exec code that is uploaded.

However such schemes often have big security holes and allows untested code to run on prod .. 

Once you have an admin service isn't it trivial  to then add new commands ? A few lines and push it and your CI should take care of the rest ( putting it on SF etc) you need to deal with dev/ test/prod anyway.

If your after one service command which seems to fine grained  just use templates to scaffold it and get your CI service to do all the SF stuff . eg take a service you have and convert it to a yeoman template. It will create the service after a few questions  and you can add the command and publish it.

**Comment by amanbha** [comment]
Please see thsi for further inforamtion on direction Service Fabric is taking for Serverless: https://azure.microsoft.com/en-us/blog/azure-service-fabric-at-microsoft-build-2018/
