### ISSUE TITLE
F# support?

### ISSUE THREAD

**Issue by o1lo01ol1o** [Microsoft/service-fabric-services-and-actors-dotnet#61]
Hi, as per [here](https://github.com/Azure/service-fabric-issues/issues/375), do you have any materials for F# as far as services or actors are concerned?  The code shouldn't be hard to translate but I haven't been able to get a working combination of `fsproj`, sf `.xml`s, and F# code.  The only examples I've found on the net are quite old.

**Comment by bklooste** [comment]
I haven't tried it so I may be talking garbage . Are your trying on Windows or Linux .. 
If I was going to try id be looking at the Linux tooling ( which can run on non Linux )  via sudo npm install -g generator-azuresfcsharp  . 

As that tooling has a much lower level of project/ visual studio  dependencies..   The cli commands to install are in scripts but that's trivial. 

Id be interested how you go ... Obviously worst case you can have a c# stub project  that calls f#.

**Comment by amanbha** [comment]
Closing due to lack of responses on this, please feel free to reopen. SF team is not planning to provide F# support for the programming models.
