### ISSUE TITLE
Cannot use Remoting v1 in .NET SDK project targeting net461

### ISSUE THREAD

**Issue by jirikopecky** [Microsoft/service-fabric-services-and-actors-dotnet#94]
Remoting stack v1 cannot be used from project that targets .NET Framework 4.6.1 and is in the new .NET SDK format - compilation fails with following error:
error CS0234: The type or namespace name 'V1' does not exist in the namespace 'Microsoft.ServiceFabric.Services.Remoting' (are you missing an assembly reference?)

Minimal repro available here: https://github.com/jirikopecky/service-fabric-sdk-remotingv1-issue

**Comment by amanbha** [comment]
@hrushib  with the new .csproj format, it seems to be adding the netstandard 2.0 version as reference since 4.6.1 is netstandard 2.0. Do we need to repackage the binaries in nuget differently?

**Comment by jirikopecky** [comment]
Any news? This issue efficiently block us from upgrading Service Fabric SDK libraries in our projects

**Comment by deepakjangid-MSFT** [comment]
The fix will be available in 2-3 weeks.

**Comment by amanbha** [comment]
@jirikopecky The fix would be in one of our future releases in coming weeks as suggested by @deepakjangid-MSFT above (can't confirm the exact nuget build number yet.).
Till then as a workaround you can use the older .csproj format instead of the new .net SDK format.

**Comment by jirikopecky** [comment]
Hi, are there any updates or ETA for this fix?

**Comment by deepakjangid-MSFT** [comment]
The new bits are planned to be shipped in a week. Will update this thread when the bits are released.

**Comment by deepakjangid-MSFT** [comment]
Same as 
https://github.com/Azure/service-fabric-issues/issues/930

**Comment by amanbha** [comment]
Fix available in Microsoft.ServiceFabric.Services.Remoting nuget package version >= 3.1.283
